routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource("promotions", "PromotionController");
Route::resource("modules", "ModuleController");
Route::resource("students", "StudentController");

app/Promotion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Promotion extends Model
{
    public function modules(){
        return $this->belongsToMany(Module::class, 'promotion_module');
    }
    public function students() {
        return $this->hasMany(Student::class);
    }
}

app/Http/Controllers/PromotionController.php
<?php

namespace App\Http\Controllers;

use App\Promotion;
use App\Module;
use App\Student;
use Illuminate\Http\Request;

class PromotionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $promotions = Promotion::all();
        $search = $request->search;
        if (!(empty($search))) {
            $promotions = Promotion::where('name', 'like', '%' . $search . '%')
            ->get();
        }
        return view('promotions.index', ['promotions' => $promotions, 'search' => $search]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $modules = Module::all();
        $students = Student::whereNull('promotion_id')->get();

        return view('promotions.create', 
        ['modules' => $modules,
         'students' => $students]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $newPromotion = new Promotion();
        $newPromotion->name = $request->name;
        $newPromotion->speciality = $request->speciality;
        $newPromotion->save();

        $students = $request->students;
        if(!(empty($students))){
            foreach($students as $key => $value){
                $student = Student::find($value);
                $student->promotion_id = $newPromotion->id;
                $student->modules()->attach($request->modules);
                $student->save();
            }
        }
        

        $newPromotion->modules()->attach($request->modules);

        return redirect(route('promotions.show', ['promotion' => $newPromotion]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Promotion  $promotion
     * @return \Illuminate\Http\Response
     */
    public function show(Promotion $promotion)
    {
        return view('promotions.show', ['promotion' => $promotion]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Promotion  $promotion
     * @return \Illuminate\Http\Response
     */
    public function edit(Promotion $promotion)
    {
        $modules = Module::all();
        $freeStudents = Student::whereNull('promotion_id')->get();

        return view('promotions.edit', [
            'promotion' => $promotion,
            'modules' => $modules,
            'freeStudents' => $freeStudents]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Promotion  $promotion
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Promotion $promotion)
    {
        $promotionUpdate = Promotion::find($promotion->id);
        $promotionUpdate->name = $request->name;
        $promotionUpdate->speciality = $request->speciality;
        $promotionUpdate->save();

        $promotion->students()->each(function ($student) {
            $student->promotion_id = NULL;
            $student->push();
        });
        $students = $request->students;

        if(!(empty($students))){
            foreach($students as $key => $value){
                $student = Student::find($value);
                $student->modules()->detach();
                $student->modules()->attach($request->modules);
                $student->promotion_id = $promotion->id;
                $student->push();
            }
        }

        $promotion->modules()->detach();
		$promotion->modules()->attach($request->modules);

        return redirect(route('promotions.show', ['promotion' => $promotion]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Promotion  $promotion
     * @return \Illuminate\Http\Response
     */
    public function destroy(Promotion $promotion, Request $request)
    {
        $promotion->delete();
        $promotion->modules()->detach();

        if(isset($request->deleteAll)){
            $promotion->students()->each(function($student){
                $student->modules()->detach();
                $student->delete();
            });
        }else{
            $promotion->students()->each(function ($student) {
                $student->modules()->detach();
                $student->promotion_id = NULL;
                $student->push();
            });
        }

        return redirect(route('promotions.index'));
    }
}

resources/views/promotions/create.blade.php
@extends('layouts.app')

@section('title')
Création de la promotion
@endsection

@section('body-title')
Création de la promotion
@endsection

@section('content')

<style>
    #btn_add_promo {
        margin-top: 2%;
        padding-left: 47%;
    }

    .tab {
        overflow: hidden;
        border: 1px solid #ccc;
        background-color: #f1f1f1;
    }

    .tab button {
        background-color: inherit;
        float: left;
        border: none;
        outline: none;
        cursor: pointer;
        padding: 14px 16px;
        transition: 0.3s;
        font-size: 17px;
    }

    .tab button:hover {
        background-color: #ddd;
    }

    .tab button.active {
        background-color: #ccc;
    }

    .tabcontent {
        display: none;
        padding: 6px 12px;
        border: 1px solid #ccc;
        border-top: none;
    }
</style>

<form method="POST" action="{{ route('promotions.store') }}">
    @csrf

    <div class="tab">
        <button class="tablinks" onclick="openCity(event, 'niv_etude')"> Niveau d'étude </button>
        <button class="tablinks" onclick="openCity(event, 'Filiere')"> Filière </button>
        <button class="tablinks" onclick="openCity(event, 'Modules')">Modules</button>
        <button class="tablinks" onclick="openCity(event, 'Eleves')"> Elèves restant </button>
    </div>
    <div id="niv_etude" class="tabcontent">
        <div class="mb-3">
            <label for="name" style="font-size: 20px"> Niveau d'étude :</label>
            <input type="text" class="form-control form-control-lg" name="name" placeholder="B1, B2, .." required>
        </div>
    </div>

    <div id="Filiere" class="tabcontent">
        <div class="mb-3">
            <label for="speciality" style="font-size: 20px"> Filière :</label>
            <input type="text" class="form-control form-control-lg" name="speciality" placeholder="Informatique, CréaDesign, .." required>
        </div>
    </div>

    <div id="Modules" class="tabcontent">
        <div class="row">
            @foreach ($modules as $module)
            <div class="col-sm-4">
                <div class="mb-3 form-check">
                    <label class="form-check-label" for="module-{{ $module->id }}">{{ $module->name }}</label>
                    <input type="checkbox" class="form-check-input" id="module-{{ $module->id }}" value="{{ $module->id }}" name="modules[]">
                </div>
            </div>
            @endforeach
        </div>
    </div>
    <div id="Eleves" class="tabcontent">
        <div class="row">
            @foreach ($students as $student)
            <div class="col-sm-4">
                <div class="mb-3 form-check">
                    <label class="form-check-label" for="student-{{ $student->id }}">{{ $student->name }} {{ $student->firstName }}</label>
                    <input type="checkbox" class="form-check-input" id="student-{{ $student->id }}" value="{{ $student->id }}" name="students[]">
                </div>
            </div>
            @endforeach
        </div>
    </div>

    <div id="btn_add_promo">
        <button type="submit" class="d-block btn btn-dark text-white"> Valider </button>
    </div>
</form>

@endsection

<script>
    function openCity(evt, cityName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " active";
    }
</script>

resources/views/promotions/edit.blade.php
@extends('layouts.app')

@section('title')
Gestion de la promotion
@endsection

@section('body-title')
Gestion de la promotion
@endsection

<style>
    #btn_add_promo {
        margin-top: 2%;
        padding-left: 47%;
    }

    .tab {
        overflow: hidden;
        border: 1px solid #ccc;
        background-color: #f1f1f1;
    }

    .tab button {
        background-color: inherit;
        float: left;
        border: none;
        outline: none;
        cursor: pointer;
        padding: 14px 16px;
        transition: 0.3s;
        font-size: 17px;
    }

    .tab button:hover {
        background-color: #ddd;
    }

    .tab button.active {
        background-color: #ccc;
    }

    .tabcontent {
        display: none;
        padding: 6px 12px;
        border: 1px solid #ccc;
        border-top: none;
    }
</style>

@section('content')

<form method="POST" action="{{ route('promotions.update', ['promotion'=> $promotion]) }}">
    @method("PUT")
    @csrf

    <div class="tab">
        <button class="tablinks" onclick="openCity(event, 'niv_etude')"> Niveau d'étude </button>
        <button class="tablinks" onclick="openCity(event, 'Filiere')"> Filière </button>
        <button class="tablinks" onclick="openCity(event, 'Modules')">Modules</button>
        <button class="tablinks" onclick="openCity(event, 'eleves_Promo')"> Elèves de la promo </button>
        <button class="tablinks" onclick="openCity(event, 'eleves_Restant')"> Elèves sans promotion </button>
    </div>

    <div id="niv_etude" class="tabcontent">
        <div class="mb-3">
            <input type="text" class="form-control form-control-lg" name="name" placeholder="B1, B2, .." required>
        </div>
    </div>

    <div id="Filiere" class="tabcontent">
        <div class="mb-5">
            <input type="text" class="form-control form-control-lg" name="speciality" placeholder=" Informatique, Marketing, .." required>
        </div>
    </div>

    <div id="Modules" class="tabcontent">
        <div class="row">
            <div class="col-4">
                <div class="row">
                    @foreach($modules as $module)
                    <div class="col-5 mb-4 form-check" style="margin-left: 20px">
                        <input type="checkbox" class="form-check-input" id="module-{{ $module->id }}" value="{{ $module->id }}" name="modules[]" @foreach($promotion->modules as $possibleModule)
                        @if($possibleModule->id == $module->id) checked @endif
                        @endforeach
                        >
                        <label class="form-check-label" for="module-{{ $module->id }}">{{ $module->name }}</label>
                    </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>

    <div id="eleves_Promo" class="tabcontent">
        <div class="col-4">
            <div class="row">
                @foreach($promotion->students as $student)
                <div class="col-5 mb-4 form-check" style="margin-left: 20px">
                    <input type="checkbox" class="form-check-input" id="student-{{ $student->id }}" value="{{ $student->id }}" name="students[]" checked>
                    <label class="form-check-label" for="student-{{ $student->id }}">{{ $student->name }} {{ $student->firstName }}</label>
                </div>
                @endforeach
            </div>
        </div>
    </div>

    <div id="eleves_Restant" class="tabcontent">
        <div class="col-4">
            <div class="row">
                @foreach($freeStudents as $freeStudent)
                <div class="col-5 mb-4 form-check" style="margin-left: 20px">
                    <input type="checkbox" class="form-check-input" id="student-{{ $freeStudent->id }}" value="{{ $freeStudent->id }}" name="students[]">
                    <label class="form-check-label" for="student-{{ $freeStudent->id }}">{{ $freeStudent->name }} {{ $freeStudent->firstName }}</label>
                </div>
                @endforeach
            </div>
        </div>
    </div>

    <div id="btn_add_promo">
        <button type="submit" class="d-block btn btn-dark text-white"> Valider </button>
    </div>

</form>


@endsection

<script>
    function openCity(evt, cityName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " active";
    }
</script>

resources/views/promotions/index.blade.php
@extends('layouts.app')

@section('title')
Promotions
@endsection

@section('body-title')
Promotion des différentes filières
@endsection



@section('content')

<style>
    body {
        background-color: #ececec;
    }

    .column {
        margin-left: 35%;
    }

    #test {
        background-color: #d3d3d3;
    }

    .gg-info {
        margin-top: 7%;
        margin-left: 40%;
        margin-bottom: 3%;
    }

    .gg-menu-hotdog {
        margin-top: 8%;
        margin-left: 40%;
        margin-bottom: 10%;
    }

    .gg-trash {
        margin-top: 10%;
        margin-left: 45%;
        margin-bottom: 10%;
    }

    .btn_add_promo {
        margin-left: 30%;
    }
</style>

<div class="column">

    @foreach ( $promotions as $promotion)
    <div class="col-xl-4">
        <div id="test" class="card text-center" style="width: 25rem; margin-bottom: 10px; margin-top: 10px;">
            <div class="card-body">
                <h5 class="card-title mb-4">{{ $promotion->name }} - {{ $promotion->speciality }}</h5>
            </div>

            <div class="row">
                <div class="col-sm-4 ">
                    <a href="{{ route('promotions.show', ['promotion' => $promotion]) }}" class="d-block btn btn-warning text-white"><i class="gg-info"></i></a>
                </div>
                <div class="col-sm-4 ">
                    <a href="{{ route('promotions.edit', ['promotion' => $promotion]) }}" class="d-block btn btn-dark text-white"><i class="gg-menu-hotdog"></i></a>
                </div>
                <div class="col-sm-4 ">
                    <form class="d-grid" method="POST" action="{{route('promotions.destroy', ['promotion' => $promotion] )}}">
                        @method("DELETE")
                        @csrf
                        <button type="submit" class="d-block btn btn-danger text-white"><i class="gg-trash"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </div>


    @endforeach
</div>

<div id="btn_add_promo">
    <a class="d-block btn btn-dark text-white" href="{{ route('promotions.create') }}"> Créer une Promotion </a>
</div>

@endsection

resources/views/promotions/show.blade.php
@extends('layouts.app')

@section('title')
Informations Promotion
@endsection

@section('content')

<style>
    .gg-menu-hotdog {
        margin-top: 8%;
        margin-left: 40%;
        margin-bottom: 10%;
    }

    .gg-trash {
        margin-top: 10%;
        margin-left: 45%;
        margin-bottom: 10%;
    }

    .img_Promo {
        position: absolute;
        padding-right: 80%;

    }

    .tab {
        overflow: hidden;
        border: 1px solid #ccc;
        background-color: #f1f1f1;
    }

    .tab button {
        background-color: inherit;
        float: left;
        border: none;
        outline: none;
        cursor: pointer;
        padding: 14px 16px;
        transition: 0.3s;
        font-size: 17px;
    }

    .tab button:hover {
        background-color: #ddd;
    }

    .tab button.active {
        background-color: #ccc;
    }

    .tabcontent {
        display: none;
        padding: 6px 12px;
        border: 1px solid #ccc;
        border-top: none;
    }

    #div_btn_promo {
        margin-left: 40%;
        margin-top: 1%;
    }
</style>

<div class="column">
    <img src="/img/toulouse_promo.png" class="img_Promo" alt="Ynov">

    <div class="col-md-8 text-center" style="margin-left: 15%">
        <div class="card-body">
            <h3 class="card-title">{{ $promotion->name }} | {{ $promotion->speciality }}</h3><br>
            <p style="font-size: 16px"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus rhoncus eget tellus
                id posuere. Nam suscipit eros suscipit mollis egestas. Etiam pharetra, mauris ut tincidunt faucibus,
                est neque fermentum dolor, id vulputate. </p>
        </div>
    </div>

    <div class="tab">
        <button class="tablinks" onclick="openCity(event, 'Modules')">Modules</button>
        <button class="tablinks" onclick="openCity(event, 'Eleves')"> Elèves </button>
    </div>

    <div id="Modules" class="tabcontent">
        @if (isset($promotion->modules[0]))
        @endif
        <div class="row" style="margin-top: 2%;">
            @include('modules.parts.listModule', ['collection'=>$promotion->modules])
        </div>
    </div>

    <div id="Eleves" class="tabcontent">
        @if (isset($promotion->students[0]))
        @endif
        <div class="row mb-4">
            @include('students.parts.listStudent', ['collection'=>$promotion->students, 'button'=> 'no'])
        </div>
    </div>


    <div id="div_btn_promo" class="d-flex flex-row mb-3">
        <div style="margin-right: 2%">
            <a href="{{ route('promotions.edit', ['promotion' => $promotion]) }}" class="d-block btn btn-dark "><i class="gg-menu-hotdog"></i> Configurer </a>
        </div>
        <div>
            <form method="POST" action="{{route('promotions.destroy', ['promotion' => $promotion] )}}" style="margin-right: 10px">
                @method("DELETE")
                @csrf
                <button type="submit" class="d-block btn btn-danger text-white"><i class="gg-trash"></i> Supprimer </button>
            </form>
        </div>
    </div>
</div>
@endsection

<script>
    function openCity(evt, cityName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " active";
    }
</script>