routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource("promotions", "PromotionController");
Route::resource("modules", "ModuleController");
Route::resource("students", "StudentController");

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    public function promotion(){
        return $this->belongsTo(Promotion::class);
    }
    public function modules(){
        return $this->belongsToMany(Module::class, 'student_module');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Module;
use App\Promotion;
use App\Student;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $promotions = Promotion::orderBy('name', 'asc')->get();
        $arrayStudent = array();

        foreach($promotions as $key => $value){
            $promotionNameSpeciality = $value->name . ' ' .$value->speciality ;
            $tmp = array('promotionNameSpeciality' =>$promotionNameSpeciality  ,
                        'student' => array());
            foreach($value->students as $k => $student){
                array_push($tmp['student'], $student);
            }
            array_push($arrayStudent, $tmp);
        }

        $freestudents = Student::whereNull('promotion_id')->get();

        $students='';
        $search = $request->search;
        if (!(empty($search))) {
            $students = Student::where('name', 'like', '%' . $search . '%')
            ->orWhere('firstName', 'like', '%' . $search . '%')
            ->orWhere('email', 'like', '%' . $search . '%')
            ->get();
        }
        return view('students.index', [
            'freestudents' => $freestudents,
            'promotions' => $arrayStudent, 
            'search' => $search,
            'studentsSearch' => $students]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $promotions = Promotion::all();
        $modules = Module::all();
        return view('students.create', ['modules' => $modules, 'promotions' => $promotions]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $newStudent = new Student();
        $newStudent->name = $request->name;
        $newStudent->firstName = $request->firstName;
        $newStudent->email = $request->email;
        $newStudent->promotion_id = $request->promotion;
        $newStudent->save();

        if(isset($request->promotion)){
            $promotion = Promotion::find($request->promotion);
            if(isset($request->modules)){
                $modulesOfPromotion = $promotion->modules;
                $modulesOfInputs = $request->modules;

                foreach($modulesOfPromotion as $key => $module){
                    if(!in_array($module->id, $modulesOfInputs)){
                        $modulesOfInputs[] += $module->id;
                    }
                }

                foreach($modulesOfInputs as $key => $value){
                    $module = Module::find($value);
                    $module->students()->attach($newStudent);
                }

            }else{
                $newStudent->modules()->attach($promotion->modules());
            }
        
        }
        elseif(isset($request->modules)){
            $newStudent->modules()->attach($request->modules);
        }

        return redirect(route('students.show', ['student'=>$newStudent]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        return view('students.show', ['student'=>$student]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        $promotions = Promotion::all();
        $modules = Module::all();
        return view('students.edit', [
            'student' => $student,
            'promotions' => $promotions,
            'modules' => $modules]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        print_r($request->all());
        $studentUpdate = Student::find($student->id);
        $studentUpdate->name = $request->name;
        $studentUpdate->firstName = $request->firstName;
        $studentUpdate->email = $request->email;
        if($request->promotion == 'no_promotion'){
            $studentUpdate->promotion_id = NULL;
        }else{
            $studentUpdate->promotion_id = $request->promotion;
        }
        $studentUpdate->save();

        $studentUpdate->modules()->detach();
        $studentUpdate->modules()->attach($request->modules);

        return redirect(route('students.show', ['student'=> $studentUpdate]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        $student->modules()->detach();
        $student->delete();
        return redirect(route('students.index'));
    }
}

resources/views/students/create.blade.php
@extends('layouts.app')

@section('title')
Students Creation
@endsection

@section('body-title')
Students Creation
@endsection

@section('content')

<form method="POST" action="{{ route("students.store") }}">
    @csrf
    <div class="mb-3">
        <label for="name" style="font-size: 20px">Student's Name :</label>
        <input type="text" class="form-control form-control-lg" name="name" placeholder="Entrer a Student's name" required>
    </div>

    <div class="mb-3">
        <label for="firstName" style="font-size: 20px">Student's First Name :</label>
        <input type="text" class="form-control form-control-lg" name="firstName" placeholder="Entrer a Student's First Name" required>
    </div>

    <div class="mb-3">
        <label for="email" style="font-size: 20px">Student's email :</label>
        <input type="email" class="form-control form-control-lg" name="email" placeholder="Entrer a Student's email" required>
    </div>
    <br>

    <h3>Add this Student to a Promotion* :</h3>
    <p><small>* Add a student to a promotion will add all promotion's module to the student and you can add aditional module.</small></p>

    <br>
    <div class="row">
        @foreach ($promotions as $promotion)
        <div class="col-sm-4">
            <div class="mb-3 form-check">
                <label class="form-check-label" for="promotion-{{ $promotion->id }}">{{ $promotion->name }} {{ $promotion->speciality }}</label>
                <input type="radio" class="form-check-input" id="promotion-{{ $promotion->id }}" value="{{ $promotion->id }}" name="promotion">
            </div>
        </div>
        @endforeach
    </div>
    <br>

    <h3>Add this Student to a Module : </h3>
    <br>
    <div class="row">
        @foreach ($modules as $module)
        <div class="col-sm-4">
            <div class="mb-3 form-check">
                <label class="form-check-label" for="module-{{ $module->id }}">{{ $module->name }}</label>
                <input type="checkbox" class="form-check-input" id="module-{{ $module->id }}" value="{{ $module->id }}" name="modules[]">
            </div>
        </div>
        @endforeach
    </div>
    <br>

    <button type="submit" class="btn btn-lg btn-success">Create the Student</button>
</form>

@endsection

resources/views/students/edit.blade.php
@extends('layouts.app')

@section('title')
Edition de l'élève
@endsection

<style>
    h1 {
        text-align: center;
        text-decoration: underline;
    }

    #btn_add_student {
        margin-top: 2%;
        padding-left: 47%;
    }

    .btn_edit_student {
        margin-top: 5%;
    }

    .tab {
        overflow: hidden;
        border: 1px solid #ccc;
        background-color: #f1f1f1;
    }

    .tab button {
        background-color: inherit;
        float: left;
        border: none;
        outline: none;
        cursor: pointer;
        padding: 14px 16px;
        transition: 0.3s;
        font-size: 17px;
    }

    .tab button:hover {
        background-color: #ddd;
    }

    .tab button.active {
        background-color: #ccc;
    }

    .tabcontent {
        display: none;
        padding: 6px 12px;
        border: 1px solid #ccc;
        border-top: none;
    }
</style>


@section('content')

<h1> Edition de l'étudiant </h1>
<br>

<form method="POST" action="{{ route('students.update', ['student'=>$student]) }}">
    @method("PUT")
    @csrf

    <div class="tab">
        <button class="tablinks" onclick="openCity(event, 'etudiant')"> Etudiant </button>
    </div>

    <div id="etudiant" class="tabcontent">
        <div class="mb-3">
            <input type="text" class="form-control form-control-lg" name="name" placeholder="Nom de famille" required>
        </div>
        <div class="mb-3">
            <input type="text" class="form-control form-control-lg" name="firstName" placeholder="Prénom" required>
        </div>
        <div class="mb-3">
            <input type="email" class="form-control form-control-lg" name="email" placeholder="@" required>
        </div>

        <h4> Ajouter l'édutiant à la promotion :</h4>
        <br>
        <div class="row">
            @foreach ($promotions as $promotion)
            <div class="col-sm-4">
                <div class="mb-3 form-check">
                    <input type="radio" class="form-check-input" id="promotion-{{ $promotion->id }}" value="{{ $promotion->id }}" name="promotion" @if(isset($student->promotion) && $promotion->id == $student->promotion->id ) checked @endif
                    >
                    <label class="form-check-label" for="promotion-{{ $promotion->id }}">{{ $promotion->name }} {{ $promotion->speciality }}</label>
                </div>
            </div>
            @endforeach
        </div>
        <h4> Ajouter l'étudiant à un module : </h3>
            <br>
            <div class="row">
                @foreach ($modules as $module)
                <div class="col-sm-4">
                    <div class="mb-3 form-check">
                        <label class="form-check-label" for="module-{{ $module->id }}">{{ $module->name }}</label>
                        <input type="checkbox" class="form-check-input" id="module-{{ $module->id }}" value="{{ $module->id }}" name="modules[]" @foreach($student->modules as $possibleModule)
                        @if($possibleModule->id == $module->id) checked @endif
                        @endforeach
                        >
                    </div>
                </div>
                @endforeach
            </div>
    </div>

    <div id="btn_edit_student">
        <a class="d-block btn btn-dark text-white" href="{{ route('promotions.create') }}"> Valider l'édition </a>
    </div>
</form>

@endsection

<script>
    function openCity(evt, cityName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " active";
    }
</script>

resources/views/students/index.blade.php
@extends('layouts.app')

@section('title')
Liste des élèves
@endsection

<style>
    h1 {
        text-align: center;
        text-decoration: underline;
    }

    #btn_add_student {
        margin-top: 2%;
        padding-left: 47%;
    }
</style>

@section('content')

<h1> Liste des étudiants </h1>
<br>

<div class="row">

    @if($search)
    @include('students.parts.listStudent', ['collection'=>$studentsSearch, 'button'=> 'yes'])

    @else
    <h2 class="mb-5"> Nouveau(x) étudiant(s)</h2>
    @include('students.parts.listStudent', ['collection'=>$freestudents, 'button'=> 'yes'])

    @foreach ($promotions as $promotion)
    <h2 class="mb-5">{{ $promotion['promotionNameSpeciality'] }} :</h2>
    @include('students.parts.listStudent', ['collection'=>$promotion['student'], 'button'=> 'yes'])
    @endforeach

    @endif
</div>

<div id="btn_add_student">
    <button type="submit" class="d-block btn btn-dark text-white"> Ajouter un étudiant </button>
</div>

@endsection

resources/views/students/show.blade.php
@extends('layouts.app')

@section('title')
Elèves Infos
@endsection

@section('content')

<style>
  .student_info {
    margin-left: 38%;
    margin-bottom: 3%;
  }

  .gg-menu-hotdog {
    margin-top: 8%;
    margin-left: 40%;
    margin-bottom: 13%;
  }


  .gg-trash {
    margin-top: 10%;
    margin-left: 45%;
    margin-bottom: 10%;
  }

  .tab {
    overflow: hidden;
    border: 1px solid #ccc;
    background-color: #f1f1f1;
  }

  .tab button {
    background-color: inherit;
    float: left;
    border: none;
    outline: none;
    cursor: pointer;
    padding: 14px 16px;
    transition: 0.3s;
    font-size: 17px;
  }

  .tab button:hover {
    background-color: #ddd;
  }

  .tab button.active {
    background-color: #ccc;
  }

  .tabcontent {
    display: none;
    padding: 6px 12px;
    border: 1px solid #ccc;
    border-top: none;
  }

  #div_btn_student {
    margin-left: 40%;
    margin-top: 1%;
  }

  #btn_stu {
    margin-left: 39%;
    padding-left: 1%;
    width: 250px;
  }
</style>


<div class="column">
  <div class="student_info">
    <div class="row g-0">
      <div class="col-md-4 text-center" style="margin-top: 10%">
        <div class="card-body">
          <h5 class="card-title" style="font-size: 24px">{{ $student->name }} {{ $student->firstName }}</h5><br>
          <p class="card-text"> Adresse mail : {{ $student->email }}</p>
          <p class="card-text"><small class="text-muted"> Etudiant créer le : {{ $student->created_at }}</small></p>
          <p class="card-text"><small class="text-muted"> Mise à jour de l'étudiant le : {{ $student->updated_at }}</small></p>
        </div>
      </div>
    </div>
  </div>

  <div class="tab">
    <button class="tablinks" onclick="openCity(event, 'Promotion')"> Promotion </button>
    <button class="tablinks" onclick="openCity(event, 'Modules')"> Modules </button>
  </div>

  <div id="Promotion" class="tabcontent">
    @if (isset($student->promotion))
    <h5 class="card-title" style="font-size: 21px">{{ $student->promotion->name }} | {{ $student->promotion->speciality }}</h5><br>
    <p style="font-size: 14px"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus rhoncus eget tellus
      id posuere. Nam suscipit eros suscipit mollis egestas. Etiam pharetra, mauris ut tincidunt faucibus,
      est neque fermentum dolor, id vulputate. </p>
    <a href="{{route('promotions.show', ['promotion'=>$student->promotion])}}" id="btn_stu" class="d-block btn btn-warning text-white"><i class="gg-info"></i></a>
    @endif
  </div>

  <div id="Modules" class="tabcontent">
    @if (isset($student->modules[0]))
    @endif
    <div class="row">
      @include('modules.parts.listModule', ['collection'=>$student->modules])
    </div>
  </div>

  <div id="div_btn_student" class="d-flex flex-row mb-3">
    <div style="margin-right: 2%">
      <a href="{{ route('students.edit', ['student' => $student]) }}" class="d-block btn btn-dark "><i class="gg-menu-hotdog"></i> Configurer </a>
    </div>
    <div>
      <form method="POST" action="{{route('students.destroy', ['student' => $student] )}}" style="margin-right: 10px">
        @method("DELETE")
        @csrf
        <button class="d-block btn btn-danger text-white"><i class="gg-trash"></i> Supprimer </button>
      </form>
    </div>
  </div>

  @endsection

  <script>
    function openCity(evt, cityName) {
      var i, tabcontent, tablinks;
      tabcontent = document.getElementsByClassName("tabcontent");
      for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
      }
      tablinks = document.getElementsByClassName("tablinks");
      for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
      }
      document.getElementById(cityName).style.display = "block";
      evt.currentTarget.className += " active";
    }
  </script>