routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource("promotions", "PromotionController");
Route::resource("modules", "ModuleController");
Route::resource("students", "StudentController");

resources/views/layouts/app.blade.php
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"  rel="stylesheet">
    <link href='https://css.gg/info.css' rel='stylesheet'>
    <link href='https://css.gg/menu-hotdog.css' rel='stylesheet'>
    <link href='https://css.gg/trash.css' rel='stylesheet'>
    <link href='https://css.gg/search.css' rel='stylesheet'>
    

    <title>@yield('title')</title>
    
</head>
<body>
    @include('layouts.navbar')
    <div class="container">
        <br>
        <h3>
            @yield('body-title')
        </h3>
        <br>
        @yield('content')
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</body>
</html>

resources/views/layouts/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <img src="/img/LOGO_YNOV.png">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="{{ route('promotions.index') }}"> Edition des promotions </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{ route('modules.index') }}"> Edition des modules </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{ route('students.index') }}"> Edition des élèves </a>
        </li>
      </ul>

      <form class="d-flex" style="margin-top: 10px">
        <input class="form-control me-2" name='search' type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-warning" type="submit"><i class="gg-search"></i></button>
      </form>
    </div>
</nav>