routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource("promotions", "PromotionController");
Route::resource("modules", "ModuleController");
Route::resource("students", "StudentController");

app/Module.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Module extends Model
{
    public function promotions(){
        return $this->belongsToMany(Promotion::class, 'promotion_module');
    }
    public function students(){
        return $this->belongsToMany(Student::class, 'student_module');
    }
}

app/Http/Controllers/ModuleController.php
<?php

namespace App\Http\Controllers;

use App\Module;
use App\Promotion;
use App\Student;
use Illuminate\Http\Request;

class ModuleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $modules = Module::all();
        $search = $request->search;
        if (!(empty($search))) {
            $modules = Module::where('name', 'like', '%' . $search . '%')
            ->get();
        }
        return view('modules.index', ['modules' => $modules, 'search' => $search]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $promotions = Promotion::all();
        return view('modules.create', ['promotions' => $promotions]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $newModule = new Module();
        $newModule->name = $request->name;
        $newModule->description = $request->description;
        $newModule->save();

        $promotions = $request->promotions;
        if(!(empty($promotions))){
            foreach($promotions as $key => $value){
                $promotion = Promotion::find($value);
                $students = Student::where('promotion_id', '=', $promotion->id)->get();

                $newModule->students()->attach($students);
                $newModule->promotions()->attach($promotion);
            }
        }
        return redirect(route('modules.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function show(Module $module)
    {
        return view('modules.show', ['module' => $module]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function edit(Module $module)
    {
        $promotions = Promotion::all();
        $freeStudents = Student::whereNull('promotion_id')->get();

        return view('modules.edit', 
        ['module' => $module, 
        'promotions' => $promotions,
        'freeStudents' => $freeStudents]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Module $module)
    {
        $moduleUpdate = Module::find($module->id);
        $moduleUpdate->name = $request->name;
        $moduleUpdate->description = $request->description;
        $moduleUpdate->save();

        if (isset($module->promotions[0])){
            foreach($moduleUpdate->promotions as $key =>$value){
                $promotion = Promotion::find($value->id);
                $students = Student::where('promotion_id', '=', $promotion->id)->get();
                $moduleUpdate->students()->detach($students);
                $moduleUpdate->promotions()->detach($promotion);
            };
        }
        
        $promotions = $request->promotions;
        if(!(empty($promotions))){
            foreach($promotions as $key => $value){
                $promotion = Promotion::find($value);
                $students = Student::where('promotion_id', '=', $promotion->id)->get();
                $moduleUpdate->students()->attach($students);
                $moduleUpdate->promotions()->attach($promotion);
            }
        }

        return redirect(route('modules.show', ['module' => $moduleUpdate]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Module  $module
     * @return \Illuminate\Http\Response
     */
    public function destroy(Module $module)
    {
        $module->promotions()->detach();
        $module->students()->detach();
        $module->delete();
        return redirect(route('modules.index'));
    }
}

resources/views/modules/create.blade.php
@extends('layouts.app')

@section('title')
Création d'un module
@endsection

<style>
    #btn_add_modules {
        margin-top: 2%;
        padding-left: 47%;
    }

    .tab {
        overflow: hidden;
        border: 1px solid #ccc;
        background-color: #f1f1f1;
    }

    .tab button {
        background-color: inherit;
        float: left;
        border: none;
        outline: none;
        cursor: pointer;
        padding: 14px 16px;
        transition: 0.3s;
        font-size: 17px;
    }

    .tab button:hover {
        background-color: #ddd;
    }

    .tab button.active {
        background-color: #ccc;
    }

    .tabcontent {
        display: none;
        padding: 6px 12px;
        border: 1px solid #ccc;
        border-top: none;
    }
</style>

@section('content')

<form method="POST" action="{{ route('modules.store') }}">
    @csrf

    <div class="tab">
        <button class="tablinks" onclick="openCity(event, 'module_Name')"> Nom du module </button>
        <button class="tablinks" onclick="openCity(event, 'add_promo_toModule')"> Ajouter une promotion à un module </button>
    </div>

    <div id="module_Name" class="tabcontent">
        <div class="mb-3">
            <input type="text" class="form-control form-control-lg" name="name" placeholder="IoT, Réseau,.." required>
        </div>
    </div>

    <div id="add_promo_toModule" class="tabcontent">
        <div class="row">
            @foreach ($promotions as $promotion)
            <div class="col-sm-4">
                <div class="mb-3 form-check">
                    <label class="form-check-label" for="module-{{ $promotion->id }}">{{ $promotion->name }} | {{ $promotion->speciality }}</label>
                    <input type="checkbox" class="form-check-input" id="module-{{ $promotion->id }}" value="{{ $promotion->id }}" name="promotions[]">
                </div>
            </div>
            @endforeach
        </div>
    </div>

    <div id="btn_add_modules">
        <button type="submit" class="d-block btn btn-dark text-white"> Valider </button>
    </div>
</form>

@endsection

<script>
    function openCity(evt, cityName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " active";
    }
</script>

resources/views/modules/edit.blade.php
@extends('layouts.app')

@section('title')
Infos Module
@endsection

<style>
    #btn_add_modules {
        margin-top: 2%;
        padding-left: 47%;
    }

    .tab {
        overflow: hidden;
        border: 1px solid #ccc;
        background-color: #f1f1f1;
    }

    .tab button {
        background-color: inherit;
        float: left;
        border: none;
        outline: none;
        cursor: pointer;
        padding: 14px 16px;
        transition: 0.3s;
        font-size: 17px;
    }

    .tab button:hover {
        background-color: #ddd;
    }

    .tab button.active {
        background-color: #ccc;
    }

    .tabcontent {
        display: none;
        padding: 6px 12px;
        border: 1px solid #ccc;
        border-top: none;
    }
</style>

@section('content')

<form method="POST" action="{{ route('modules.update', ['module' => $module]) }}">
    @method("PUT")
    @csrf

    <div class="tab">
        <button class="tablinks" onclick="openCity(event, 'module_Name')"> Nom du module </button>
        <button class="tablinks" onclick="openCity(event, 'list_promo_toModule')"> Liste des promotions </button>
    </div>

    <div id="module_Name" class="tabcontent">
        <div class="mb-3">
            <label for="name" style="font-size: 20px"> Nom de module :</label>
            <input type="text" class="form-control form-control-lg" name="name" value="{{$module->name}}" placeholder="Entrer a promotion's name" required>
        </div>
    </div>

    <div id="list_promo_toModule" class="tabcontent">
        <div class="row mb-3">
            @foreach($promotions as $promotion)
            <div class="col mb-4 form-check">
                <input type="checkbox" class="form-check-input" id="promotion-{{ $promotion->id }}" value="{{ $promotion->id }}" name="promotions[]" @foreach($module->promotions as $possiblePromotion)
                @if($possiblePromotion->id == $promotion->id) checked @endif
                @endforeach
                >
                <label class="form-check-label" for="promotion-{{ $promotion->id }}">{{ $promotion->name }} | {{ $promotion->speciality }}</label>
            </div>
            @endforeach
        </div>
    </div>

    <div id="btn_add_modules">
        <button type="submit" class="d-block btn btn-dark text-white"> Valider </button>
    </div>
</form>

@endsection

<script>
    function openCity(evt, cityName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " active";
    }
</script>

resources/views/modules/index.blade.php
@extends('layouts.app')

@section('title')
Liste des modules
@endsection

<style>
    body {
        background-color: #ececec;
    }

    .column {
        margin-left: 35%;
    }

    #test {
        background-color: #d3d3d3;
    }

    .gg-info {
        margin-top: 7%;
        margin-left: 40%;
        margin-bottom: 3%;
    }

    .gg-menu-hotdog {
        margin-top: 8%;
        margin-left: 40%;
        margin-bottom: 10%;
    }

    .gg-trash {
        margin-top: 50%;
        margin-left: 45%;
        margin-bottom: 10%;
    }

    .btn_add_module {
        margin-left: 30%;
    }
</style>

@section('content')
<div class="column">
    @foreach ( $modules as $module)
    <div class="col-xl-4">
        <div id="test" class="card text-center" style="width: 25rem; margin-bottom: 10px; margin-top: 10px; ">
            <div class="card-body">
                <h5 class="card-title">{{ $module->name }}</h5>

                <div class="row">
                    <div class="col-4">
                        <a href="{{route('modules.show', ['module' => $module] )}}" class="d-block btn btn-warning text-white">
                            <i class="gg-info"></i>
                        </a>
                    </div>
                    <div class="col-4">
                        <a href="{{route('modules.edit', ['module' => $module] )}}" class="d-block btn btn-dark text-white">
                            <i class="gg-menu-hotdog"></i>
                        </a>
                    </div>
                    <div class="col-4">
                        <form class="d-grid" method="POST" action="{{route('modules.destroy', ['module' => $module] )}}">
                            @method("DELETE")
                            @csrf
                            <button type="submit" class="d-block btn btn-danger text-white">
                                <i class="gg-trash"></i>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endforeach
</div>
<div id="btn_add_module">
    <a class="d-block btn btn-dark text-white" href="{{ route('modules.create') }}"> Créer un module </a>
</div>

@endsection

resources/views/modules/show.blade.php
@extends('layouts.app')

@section('title')
Infos Module
@endsection

@section('content')

<style>
    .gg-menu-hotdog {
        margin-top: 8%;
        margin-left: 40%;
        margin-bottom: 10%;
    }

    .gg-trash {
        margin-top: 10%;
        margin-left: 45%;
        margin-bottom: 10%;
    }

    .img_Promo {
        position: absolute;
        padding-right: 80%;

    }

    .tab {
        overflow: hidden;
        border: 1px solid #ccc;
        background-color: #f1f1f1;
    }

    .tab button {
        background-color: inherit;
        float: left;
        border: none;
        outline: none;
        cursor: pointer;
        padding: 14px 16px;
        transition: 0.3s;
        font-size: 17px;
    }

    .tab button:hover {
        background-color: #ddd;
    }

    .tab button.active {
        background-color: #ccc;
    }

    .tabcontent {
        display: none;
        padding: 6px 12px;
        border: 1px solid #ccc;
        border-top: none;
    }

    #div_btn_promo_detail {
        margin-left: 40%;
        margin-top: 1%;
    }
</style>

<div class="card text-center mb-3 " style="font-size: 18px">
    <div class="card-body mb-2">
        <h5 class="card-title mb-3" style="font-size: 30px">{{ $module->name }}</h5>
    </div>
    <div class="card-footer text-muted">
        <p style="font-size: 16px"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus rhoncus eget tellus
            id posuere. Nam suscipit eros suscipit mollis egestas. Etiam pharetra, mauris ut tincidunt faucibus,
            est neque fermentum dolor, id vulputate. </p>
    </div>
</div>

<div class="tab">
    <button class="tablinks" onclick="openCity(event, 'Promotion')"> Promotion </button>
    <button class="tablinks" onclick="openCity(event, 'Eleves')"> Elèves </button>
</div>

<div id="Promotion" class="tabcontent">
    @if (isset($module->promotions[0]))
    @endif
    <div class="row">
        @include('promotions.parts.listPromotion', ['collection'=>$module->promotions])
    </div>
</div>
<div id="Eleves" class="tabcontent">
    @if (isset($module->students[0]))
    @endif
    <div class="row mb-4">
        @include('students.parts.listStudent', ['collection'=>$module->students, 'button'=> 'no'])
    </div>
</div>

@endsection

<script>
    function openCity(evt, cityName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " active";
    }
</script>